version: '3.3'

services:
  web:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
