version: '3.3'

services:
  web:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - node_modules_data:/usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  mongo-data:
  node_modules_data:
